name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'hashfoundry-react/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./hashfoundry-react
          file: ./hashfoundry-react/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/hashfoundry-react:latest
            ${{ secrets.DOCKER_HUB_USER }}/hashfoundry-react:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER }}/hashfoundry-react:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USER }}/hashfoundry-react:buildcache,mode=max
